import type { AvailableTruck, PendingShipment } from './types';

/** INTEGRATION POINT: Replace with API call */
export const MOCK_TRUCKS: AvailableTruck[] = [
  {
    id: 'AV-001',
    vis: 'private',
    label: 'Shared with you',
    startDt: '21/02/2026',
    startTm: '08:00',
    endDt: '21/02/2026',
    endTm: '20:00',
    pickup: 'Ioannina',
    radius: 50,
    dest: 'Athens',
    truckType: 'Semi-Trailer',
    specs: 'Curtainside',
    capacity: '24T',
    capVal: 24,
    capUnit: 'Tonnes',
    trip: 'Multi-stop OK',
    carrier: 'Georgiadis Transport S.A.',
    initials: 'GT',
    rating: 4.2,
    type: 'Carrier',
    preferred: true,
    price: 500,
    currency: 'EUR',
    posted: '25m ago',
    recurring: true,
    occurrences: ['21/02 08:00', '22/02 08:00', '23/02 08:00'],
    recurrenceLabel: 'Daily × 3',
    onTimePickup: 94,
    cancellationRate: 3,
    avgResponseMin: 18,
  },
  {
    id: 'AV-002',
    vis: 'public',
    label: 'Public',
    startDt: '21/02/2026',
    startTm: '10:00',
    endDt: '21/02/2026',
    endTm: '22:00',
    pickup: 'Thessaloniki',
    radius: 30,
    dest: 'Any',
    truckType: 'Semi-Trailer',
    specs: 'Refrigerated',
    capacity: '20T',
    capVal: 20,
    capUnit: 'Tonnes',
    trip: 'Direct only',
    carrier: 'TransMed Logistics',
    initials: 'TM',
    rating: 4.8,
    type: 'Carrier',
    preferred: false,
    price: 650,
    currency: 'EUR',
    posted: '1h ago',
    recurring: false,
    occurrences: [],
    recurrenceLabel: '',
    onTimePickup: 97,
    cancellationRate: 1,
    avgResponseMin: 12,
  },
  {
    id: 'AV-003',
    vis: 'private',
    label: 'Shared with you',
    startDt: '21/02/2026',
    startTm: '14:00',
    endDt: '22/02/2026',
    endTm: '06:00',
    pickup: 'Ioannina',
    radius: 80,
    dest: 'Patras',
    truckType: 'Box Truck',
    specs: 'Tail lift',
    capacity: '8T',
    capVal: 8,
    capUnit: 'Tonnes',
    trip: 'Multi-stop OK',
    carrier: 'Dimitris Ntinos',
    initials: 'DN',
    rating: 5.0,
    type: 'Freelancer',
    preferred: true,
    price: null,
    currency: 'EUR',
    posted: '2h ago',
    recurring: false,
    occurrences: [],
    recurrenceLabel: '',
    onTimePickup: 99,
    cancellationRate: 0,
    avgResponseMin: 8,
  },
  {
    id: 'AV-004',
    vis: 'public',
    label: 'Public',
    startDt: '21/02/2026',
    startTm: '06:00',
    endDt: '21/02/2026',
    endTm: '18:00',
    pickup: 'Athens',
    radius: 40,
    dest: 'Thessaloniki',
    truckType: 'Semi-Trailer',
    specs: 'Flatbed',
    capacity: '26T',
    capVal: 26,
    capUnit: 'Tonnes',
    trip: 'Direct only',
    carrier: 'Papadopoulos Logistics',
    initials: 'PL',
    rating: 3.9,
    type: 'Carrier',
    preferred: false,
    price: 420,
    currency: 'EUR',
    posted: '3h ago',
    recurring: false,
    occurrences: [],
    recurrenceLabel: '',
    onTimePickup: 88,
    cancellationRate: 5,
    avgResponseMin: 25,
  },
  {
    id: 'AV-005',
    vis: 'public',
    label: 'Public',
    startDt: '22/02/2026',
    startTm: '07:00',
    endDt: '22/02/2026',
    endTm: '19:00',
    pickup: 'Larissa',
    radius: 50,
    dest: 'Any',
    truckType: 'Semi-Trailer',
    specs: 'Curtainside',
    capacity: '24T',
    capVal: 24,
    capUnit: 'Tonnes',
    trip: 'Multi-stop OK',
    carrier: 'Nikos Alexiou',
    initials: 'NA',
    rating: 4.5,
    type: 'Freelancer',
    preferred: false,
    price: 380,
    currency: 'EUR',
    posted: '45m ago',
    recurring: true,
    occurrences: ['22/02 07:00', '23/02 07:00', '24/02 07:00', '25/02 07:00'],
    recurrenceLabel: 'Daily × 4',
    onTimePickup: 92,
    cancellationRate: 2,
    avgResponseMin: 15,
  },
  {
    id: 'AV-006',
    vis: 'private',
    label: 'Shared with you',
    startDt: '21/02/2026',
    startTm: '12:00',
    endDt: '21/02/2026',
    endTm: '23:59',
    pickup: 'Patras',
    radius: 30,
    dest: 'Ioannina',
    truckType: 'Box Truck',
    specs: 'Curtainside',
    capacity: '10T',
    capVal: 10,
    capUnit: 'Tonnes',
    trip: 'Direct only',
    carrier: 'Stavrou Transport E.E.',
    initials: 'ST',
    rating: 4.7,
    type: 'Carrier',
    preferred: true,
    price: 320,
    currency: 'EUR',
    posted: '10m ago',
    recurring: false,
    occurrences: [],
    recurrenceLabel: '',
    onTimePickup: 96,
    cancellationRate: 2,
    avgResponseMin: 10,
  },
  {
    id: 'AV-007',
    vis: 'public',
    label: 'Public',
    startDt: '22/02/2026',
    startTm: '05:00',
    endDt: '22/02/2026',
    endTm: '17:00',
    pickup: 'Heraklion',
    radius: 60,
    dest: 'Athens',
    truckType: 'Semi-Trailer',
    specs: 'Curtainside',
    capacity: '24T',
    capVal: 24,
    capUnit: 'Tonnes',
    trip: 'Multi-stop OK',
    carrier: 'Manolis Freight Ltd.',
    initials: 'MF',
    rating: 4.1,
    type: 'Carrier',
    preferred: false,
    price: null,
    currency: 'EUR',
    posted: '5h ago',
    recurring: false,
    occurrences: [],
    recurrenceLabel: '',
    onTimePickup: 90,
    cancellationRate: 4,
    avgResponseMin: 22,
  },
  {
    id: 'AV-008',
    vis: 'public',
    label: 'Public',
    startDt: '23/02/2026',
    startTm: '09:00',
    endDt: '23/02/2026',
    endTm: '21:00',
    pickup: 'Volos',
    radius: 40,
    dest: 'Any',
    truckType: 'Semi-Trailer',
    specs: 'Refrigerated',
    capacity: '22T',
    capVal: 22,
    capUnit: 'Tonnes',
    trip: 'Direct only',
    carrier: 'Eleni Katsarou',
    initials: 'EK',
    rating: 4.6,
    type: 'Freelancer',
    preferred: false,
    price: 550,
    currency: 'EUR',
    posted: '30m ago',
    recurring: false,
    occurrences: [],
    recurrenceLabel: '',
    onTimePickup: 95,
    cancellationRate: 1,
    avgResponseMin: 14,
  },
];

/** INTEGRATION POINT: Replace with API call */
export const MOCK_PENDING: PendingShipment[] = [
  { sid: 'SID-81225', lane: 'Ioannina → Sklavenitis', pickup: '22/02/2026', weight: '13T', stops: 2 },
  { sid: 'SID-79998', lane: 'Ioannina → THE MART', pickup: '23/02/2026', weight: '24T', stops: 3 },
  { sid: 'SID-102245', lane: 'Ioannina → Acharnes', pickup: '21/02/2026', weight: '18T', stops: 2 },
];
