import type { AvailableTruck, PendingShipment } from './types';
import { CITY_COORDS } from './types';

function coords(city: string) {
  return CITY_COORDS[city] ?? { lat: 39.07, lng: 21.82 };
}

function destCoords(dest: string) {
  if (!dest || dest === 'Any') return { destLat: null as number | null, destLng: null as number | null };
  const c = coords(dest);
  return { destLat: c.lat, destLng: c.lng };
}

/** INTEGRATION POINT: Replace with API call */
export const MOCK_TRUCKS: AvailableTruck[] = [
  {
    id: 'AV-001',
    vis: 'private',
    label: 'Shared with you',
    startDt: '21/02/2026',
    startTm: '08:00',
    endDt: '21/02/2026',
    endTm: '20:00',
    pickup: 'Ioannina',
    radius: 50,
    dest: 'Athens',
    truckType: 'Semi-Trailer',
    specs: 'Curtainside',
    capacity: '24T',
    capVal: 24,
    capUnit: 'Tonnes',
    trip: 'Multi-stop OK',
    multiStop: true,
    carrier: 'Georgiadis Transport S.A.',
    initials: 'GT',
    rating: 4.2,
    type: 'Carrier',
    preferred: true,
    price: 500,
    currency: 'EUR',
    posted: '25m ago',
    recurring: true,
    occurrences: ['21/02/2026 08:00', '22/02/2026 08:00', '23/02/2026 08:00'],
    recurrenceLabel: 'Daily × 3',
    onTimeDeliveryPct: 94,
    cancellationRate: 3,

    pickupLat: coords('Ioannina').lat,
    pickupLng: coords('Ioannina').lng,
    ...destCoords('Athens'),
    hasBids: true,
    loadMatchScore: 88,
  },
  {
    id: 'AV-002',
    vis: 'public',
    label: 'Public',
    startDt: '21/02/2026',
    startTm: '10:00',
    endDt: '21/02/2026',
    endTm: '22:00',
    pickup: 'Thessaloniki',
    radius: 30,
    dest: 'Any',
    truckType: 'Semi-Trailer',
    specs: 'Refrigerated',
    capacity: '20T',
    capVal: 20,
    capUnit: 'Tonnes',
    trip: 'Direct only',
    multiStop: false,
    carrier: 'TransMed Logistics',
    initials: 'TM',
    rating: 4.8,
    type: 'Carrier',
    preferred: false,
    price: 650,
    currency: 'EUR',
    posted: '1h ago',
    recurring: false,
    occurrences: [],
    recurrenceLabel: '',
    onTimeDeliveryPct: 97,
    cancellationRate: 1,

    pickupLat: coords('Thessaloniki').lat,
    pickupLng: coords('Thessaloniki').lng,
    ...destCoords('Any'),
    hasBids: false,
    loadMatchScore: 62,
    isVehicleOnly: true,
    postingMode: 'vehicle',
  },
  {
    id: 'AV-003',
    vis: 'private',
    label: 'Shared with you',
    startDt: '21/02/2026',
    startTm: '14:00',
    endDt: '22/02/2026',
    endTm: '06:00',
    pickup: 'Ioannina',
    radius: 80,
    dest: 'Patras',
    truckType: 'Box Truck',
    specs: 'Tail lift',
    capacity: '8T',
    capVal: 8,
    capUnit: 'Tonnes',
    trip: 'Multi-stop OK',
    multiStop: true,
    carrier: 'Dimitris Ntinos',
    initials: 'DN',
    rating: 5.0,
    type: 'Freelancer',
    preferred: true,
    price: null,
    currency: 'EUR',
    posted: '2h ago',
    recurring: false,
    occurrences: [],
    recurrenceLabel: '',
    onTimeDeliveryPct: 99,
    cancellationRate: 0,

    pickupLat: coords('Ioannina').lat + 0.02,
    pickupLng: coords('Ioannina').lng + 0.02,
    ...destCoords('Patras'),
    hasBids: false,
    loadMatchScore: 75,
  },
  {
    id: 'AV-004',
    vis: 'public',
    label: 'Public',
    startDt: '21/02/2026',
    startTm: '06:00',
    endDt: '21/02/2026',
    endTm: '18:00',
    pickup: 'Athens',
    radius: 40,
    dest: 'Thessaloniki',
    truckType: 'Semi-Trailer',
    specs: 'Flatbed',
    capacity: '26T',
    capVal: 26,
    capUnit: 'Tonnes',
    trip: 'Direct only',
    multiStop: false,
    carrier: 'Papadopoulos Logistics',
    initials: 'PL',
    rating: 3.9,
    type: 'Carrier',
    preferred: false,
    price: 420,
    currency: 'EUR',
    posted: '3h ago',
    recurring: false,
    occurrences: [],
    recurrenceLabel: '',
    onTimeDeliveryPct: 88,
    cancellationRate: 5,

    pickupLat: coords('Athens').lat,
    pickupLng: coords('Athens').lng,
    ...destCoords('Thessaloniki'),
    hasBids: true,
    loadMatchScore: 55,
  },
  {
    id: 'AV-005',
    vis: 'public',
    label: 'Public',
    startDt: '22/02/2026',
    startTm: '07:00',
    endDt: '22/02/2026',
    endTm: '19:00',
    pickup: 'Larissa',
    radius: 50,
    dest: 'Any',
    truckType: 'Semi-Trailer',
    specs: 'Curtainside',
    capacity: '24T',
    capVal: 24,
    capUnit: 'Tonnes',
    trip: 'Multi-stop OK',
    multiStop: true,
    carrier: 'Nikos Alexiou',
    initials: 'NA',
    rating: 4.5,
    type: 'Freelancer',
    preferred: false,
    price: 380,
    currency: 'EUR',
    posted: '45m ago',
    recurring: true,
    occurrences: ['22/02/2026 07:00', '23/02/2026 07:00', '24/02/2026 07:00', '25/02/2026 07:00'],
    recurrenceLabel: 'Daily × 4',
    onTimeDeliveryPct: 92,
    cancellationRate: 2,

    pickupLat: coords('Larissa').lat,
    pickupLng: coords('Larissa').lng,
    ...destCoords('Any'),
    hasBids: false,
    loadMatchScore: 80,
  },
  {
    id: 'AV-006',
    vis: 'private',
    label: 'Shared with you',
    startDt: '21/02/2026',
    startTm: '12:00',
    endDt: '21/02/2026',
    endTm: '23:59',
    pickup: 'Patras',
    radius: 30,
    dest: 'Ioannina',
    truckType: 'Box Truck',
    specs: 'Curtainside',
    capacity: '10T',
    capVal: 10,
    capUnit: 'Tonnes',
    trip: 'Direct only',
    multiStop: false,
    carrier: 'Stavrou Transport E.E.',
    initials: 'ST',
    rating: 4.7,
    type: 'Carrier',
    preferred: true,
    price: 320,
    currency: 'EUR',
    posted: '10m ago',
    recurring: false,
    occurrences: [],
    recurrenceLabel: '',
    onTimeDeliveryPct: 96,
    cancellationRate: 2,

    pickupLat: coords('Patras').lat,
    pickupLng: coords('Patras').lng,
    ...destCoords('Ioannina'),
    hasBids: true,
    loadMatchScore: 91,
  },
  {
    id: 'AV-007',
    vis: 'public',
    label: 'Public',
    startDt: '22/02/2026',
    startTm: '05:00',
    endDt: '22/02/2026',
    endTm: '17:00',
    pickup: 'Heraklion',
    radius: 60,
    dest: 'Athens',
    truckType: 'Semi-Trailer',
    specs: 'Curtainside',
    capacity: '24T',
    capVal: 24,
    capUnit: 'Tonnes',
    trip: 'Multi-stop OK',
    multiStop: true,
    carrier: 'Manolis Freight Ltd.',
    initials: 'MF',
    rating: 4.1,
    type: 'Carrier',
    preferred: false,
    price: null,
    currency: 'EUR',
    posted: '5h ago',
    recurring: false,
    occurrences: [],
    recurrenceLabel: '',
    onTimeDeliveryPct: 90,
    cancellationRate: 4,

    pickupLat: coords('Heraklion').lat,
    pickupLng: coords('Heraklion').lng,
    ...destCoords('Athens'),
    hasBids: false,
    loadMatchScore: 40,
  },
  {
    id: 'AV-008',
    vis: 'public',
    label: 'Public',
    startDt: '23/02/2026',
    startTm: '09:00',
    endDt: '23/02/2026',
    endTm: '21:00',
    pickup: 'Volos',
    radius: 40,
    dest: 'Any',
    truckType: 'Semi-Trailer',
    specs: 'Refrigerated',
    capacity: '22T',
    capVal: 22,
    capUnit: 'Tonnes',
    trip: 'Direct only',
    multiStop: false,
    carrier: 'Eleni Katsarou',
    initials: 'EK',
    rating: 4.6,
    type: 'Freelancer',
    preferred: false,
    price: 550,
    currency: 'EUR',
    posted: '30m ago',
    recurring: false,
    occurrences: [],
    recurrenceLabel: '',
    onTimeDeliveryPct: 95,
    cancellationRate: 1,

    pickupLat: coords('Volos').lat,
    pickupLng: coords('Volos').lng,
    ...destCoords('Any'),
    hasBids: true,
    loadMatchScore: 72,
  },
];

/** INTEGRATION POINT: Replace with API call */
export const MOCK_PENDING: PendingShipment[] = [
  { id: 1, sid: 'SID-81225', lane: 'Ioannina → Sklavenitis', pickup: '22/02/2026', weight: '€ 1,200', stops: 2, exactMatch: true },
  { id: 2, sid: 'SID-79998', lane: 'Ioannina → THE MART', pickup: '23/02/2026', weight: '€ 2,400', stops: 3 },
  { id: 3, sid: 'SID-102245', lane: 'Ioannina → Acharnes', pickup: '21/02/2026', weight: '€ 1,800', stops: 2, exactMatch: true },
  { id: 4, sid: 'SID-48783', lane: 'Bhadaj Circle, Ahmedabad → Gota Chokdi Flyover', pickup: 'Athens', weight: '€ 150,000', stops: 4 },
  { id: 5, sid: 'SID-40703', lane: 'Athina → Piraeus Port', pickup: 'Athens', weight: '€ 980', stops: 1 },
  { id: 6, sid: 'SID-39112', lane: 'Thessaloniki → Larissa', pickup: 'Theo', weight: '€ 640', stops: 2 },
  { id: 7, sid: 'SID-38801', lane: 'Patras → Athens Hub', pickup: 'Patras', weight: '€ 1,050', stops: 3 },
  { id: 8, sid: 'SID-37554', lane: 'Volos → Larissa DC', pickup: 'Volos', weight: '€ 420', stops: 1 },
  { id: 9, sid: 'SID-36002', lane: 'Heraklion → Chania', pickup: 'Crete', weight: '€ 780', stops: 2, exactMatch: true },
  { id: 10, sid: 'SID-35110', lane: 'Kavala → Serres', pickup: 'Kavala', weight: '€ 510', stops: 1 },
  { id: 11, sid: 'SID-34440', lane: 'Ioannina → Thessaloniki Hub', pickup: '22/02/2026', weight: '€ 1,560', stops: 4 },
  { id: 12, sid: 'SID-33091', lane: 'Athens North → Corinth', pickup: 'Athens', weight: '€ 390', stops: 2 },
  { id: 13, sid: 'SID-32108', lane: 'Alexandroupoli → Kavala Depot', pickup: 'Alex', weight: '€ 720', stops: 3 },
  { id: 14, sid: 'SID-31055', lane: 'Lamia → Domokos', pickup: 'Lamia', weight: '€ 280', stops: 1 },
  { id: 15, sid: 'SID-29970', lane: 'Trikala → Karditsa', pickup: 'Trikala', weight: '€ 310', stops: 2 },
];
