import type { BoardItem } from './types';

export const BOARD_DATA: Record<number, BoardItem[]> = {
  // Tab 0: Needs Action
  0: [
    {
      sid: "SID-79998",
      from: "Ioannina",
      to: "Kifissos",
      status: "pending",
      statusLabel: { en: "No Carrier Check-in", el: "Χωρίς Check-in Μεταφορέα" },
      statusClass: "sts-warn",
      ms: { en: "Pickup", el: "Παραλαβή" },
      dt: { en: "21/02/2026 09:00", el: "21/02/2026 09:00" },
      carrier: "G. Pantazis",
      ci: "GP",
      rate: 580,
      ref: "—",
      vehicle: { en: "Tautliner 13.6m", el: "Κουρτίνα 13.6μ" },
      weight: { en: "12,400 kg", el: "12.400 kg" },
      cargo: { en: "Water bottles", el: "Μπουκάλια νερού" },
      distance: "310 km",
      issue: { en: "Carrier has not confirmed — pickup in 1 hour", el: "Ο μεταφορέας δεν έχει επιβεβαιώσει — παραλαβή σε 1 ώρα" },
      notes: { en: "Customer: THE MART", el: "Πελάτης: THE MART" },
      sortDate: 1771664400000
    },
    {
      sid: "SID-10331",
      from: "Ioannina",
      to: "Patras",
      status: "action",
      statusLabel: { en: "Expiring Quote", el: "Προσφορά που Λήγει" },
      statusClass: "sts-warn",
      ms: { en: "Quote expires", el: "Λήξη προσφοράς" },
      dt: { en: "21/02/2026 12:00", el: "21/02/2026 12:00" },
      carrier: "M. Tsoukalas",
      ci: "MT",
      rate: 640,
      ref: "EMET-104810",
      vehicle: { en: "Box truck 7.5T", el: "Κλειστό φορτηγό 7.5Τ" },
      weight: { en: "4,200 kg", el: "4.200 kg" },
      cargo: { en: "Olive oil cases", el: "Κιβώτια ελαιολάδου" },
      distance: "220 km",
      issue: { en: "Quote expires in 2 hours — accept or reject", el: "Η προσφορά λήγει σε 2 ώρες — αποδοχή ή απόρριψη" },
      notes: { en: "2 competing bids available", el: "Διαθέσιμες 2 ανταγωνιστικές προσφορές" },
      sortDate: 1771675200000
    },
    {
      sid: "SID-93745",
      from: "Ioannina",
      to: "Thessaloniki",
      status: "action",
      statusLabel: { en: "Missing Documents", el: "Ελλιπή Έγγραφα" },
      statusClass: "sts-risk",
      ms: { en: "Upload CMR", el: "Ανέβασμα CMR" },
      dt: { en: "Overdue", el: "Εκπρόθεσμο" },
      carrier: "KRP Transport",
      ci: "KR",
      rate: 880,
      ref: "11PAP-1031785",
      vehicle: { en: "Mega trailer", el: "Mega trailer" },
      weight: { en: "18,600 kg", el: "18.600 kg" },
      cargo: { en: "Electronics pallets", el: "Παλέτες ηλεκτρονικών" },
      distance: "280 km",
      issue: { en: "CMR waybill not uploaded — shipment blocked", el: "Το CMR δεν έχει ανεβεί — η αποστολή έχει μπλοκαριστεί" },
      notes: { en: "Carrier waiting for docs", el: "Ο μεταφορέας περιμένει έγγραφα" },
      sortDate: 1771600000000
    },
    {
      sid: "SID-44221",
      from: "Ioannina",
      to: "Lamia",
      status: "action",
      statusLabel: { en: "No Carrier", el: "Χωρίς Μεταφορέα" },
      statusClass: "sts-risk",
      ms: { en: "Assign carrier", el: "Ανάθεση μεταφορέα" },
      dt: { en: "22/02", el: "22/02" },
      carrier: "— Unassigned",
      ci: "??",
      rate: 420,
      ref: "EMET-104792",
      vehicle: { en: "Tautliner", el: "Κουρτίνα" },
      weight: { en: "8,000 kg", el: "8.000 kg" },
      cargo: { en: "PET preforms", el: "Προπλάσματα PET" },
      distance: "190 km",
      issue: { en: "No bids received — posted 48 hours ago", el: "Δεν λήφθηκαν προσφορές — δημοσιεύτηκε πριν 48 ώρες" },
      notes: { en: "Consider raising rate or calling partners", el: "Σκεφτείτε να αυξήσετε την τιμή ή να καλέσετε συνεργάτες" },
      sortDate: 1771747200000
    },
    {
      sid: "SID-88401",
      from: "Ioannina",
      to: "Volos",
      status: "action",
      statusLabel: { en: "Billing Dispute", el: "Διαφωνία Χρέωσης" },
      statusClass: "sts-warn",
      ms: { en: "Resolve", el: "Επίλυση" },
      dt: { en: "—", el: "—" },
      carrier: "D. Ntinos",
      ci: "DN",
      rate: 380,
      ref: "11PAP-1031790",
      vehicle: { en: "Box truck", el: "Κλειστό φορτηγό" },
      weight: { en: "3,100 kg", el: "3.100 kg" },
      cargo: { en: "Beverage crates", el: "Κιβώτια ποτών" },
      distance: "160 km",
      issue: { en: "Carrier claims extra €40 for waiting time", el: "Ο μεταφορέας ζητά επιπλέον €40 για χρόνο αναμονής" },
      notes: { en: "2h wait at loading dock documented", el: "Τεκμηριωμένη αναμονή 2 ωρών στην αποβάθρα φόρτωσης" },
      sortDate: 0
    }
  ],

  // Tab 1: Upcoming
  1: [
    {
      sid: "SID-81225",
      from: "Ioannina",
      to: "Fousa",
      status: "upcoming",
      statusLabel: { en: "Upcoming", el: "Προσεχές" },
      statusClass: "sts-pending",
      ms: { en: "Pickup", el: "Παραλαβή" },
      dt: { en: "20/02/2026 09:06", el: "20/02/2026 09:06" },
      carrier: "Gianneas N.",
      ci: "GN",
      rate: 580,
      ref: "EMET-104801",
      vehicle: { en: "Tautliner 13.6m", el: "Κουρτίνα 13.6μ" },
      weight: { en: "11,200 kg", el: "11.200 kg" },
      cargo: { en: "Water bottles 1.5L", el: "Μπουκάλια νερού 1.5L" },
      distance: "285 km",
      issue: null,
      notes: { en: "Regular weekly delivery", el: "Τακτική εβδομαδιαία παράδοση" },
      sortDate: 1771578360000
    },
    {
      sid: "SID-98245",
      from: "Ioannina",
      to: "Amaliada",
      status: "upcoming",
      statusLabel: { en: "Upcoming", el: "Προσεχές" },
      statusClass: "sts-pending",
      ms: { en: "Pickup", el: "Παραλαβή" },
      dt: { en: "20/02/2026 09:48", el: "20/02/2026 09:48" },
      carrier: "KRP Transport",
      ci: "KR",
      rate: 660,
      ref: "11PAP-1031795",
      vehicle: { en: "Mega trailer", el: "Mega trailer" },
      weight: { en: "15,800 kg", el: "15.800 kg" },
      cargo: { en: "Mineral water pallets", el: "Παλέτες μεταλλικού νερού" },
      distance: "340 km",
      issue: null,
      notes: { en: "Temperature sensitive — max 25°C", el: "Ευαίσθητο στη θερμοκρασία — μέγιστη 25°C" },
      sortDate: 1771580880000
    },
    {
      sid: "SID-102245",
      from: "Ioannina",
      to: "Acharnes",
      status: "upcoming",
      statusLabel: { en: "Upcoming", el: "Προσεχές" },
      statusClass: "sts-pending",
      ms: { en: "Pickup", el: "Παραλαβή" },
      dt: { en: "20/02/2026 09:54", el: "20/02/2026 09:54" },
      carrier: "KRP Transport",
      ci: "KR",
      rate: 580,
      ref: "EMET-1047709",
      vehicle: { en: "Tautliner", el: "Κουρτίνα" },
      weight: { en: "12,000 kg", el: "12.000 kg" },
      cargo: { en: "Water 0.5L", el: "Νερό 0.5L" },
      distance: "310 km",
      issue: null,
      notes: { en: "Delivery to METRO warehouse", el: "Παράδοση στην αποθήκη METRO" },
      sortDate: 1771581240000
    },
    {
      sid: "SID-51222",
      from: "Ioannina",
      to: "Acharnes",
      status: "upcoming",
      statusLabel: { en: "Upcoming", el: "Προσεχές" },
      statusClass: "sts-pending",
      ms: { en: "Pickup", el: "Παραλαβή" },
      dt: { en: "20/02/2026 09:56", el: "20/02/2026 09:56" },
      carrier: "KRP Transport",
      ci: "KR",
      rate: 580,
      ref: "EMET-1047743",
      vehicle: { en: "Tautliner", el: "Κουρτίνα" },
      weight: { en: "11,800 kg", el: "11.800 kg" },
      cargo: { en: "Water 1L", el: "Νερό 1L" },
      distance: "310 km",
      issue: null,
      notes: { en: "Same destination as SID-102245", el: "Ίδιος προορισμός με SID-102245" },
      sortDate: 1771581360000
    },
    {
      sid: "SID-73019",
      from: "Ioannina",
      to: "Chalkida",
      status: "upcoming",
      statusLabel: { en: "Upcoming", el: "Προσεχές" },
      statusClass: "sts-pending",
      ms: { en: "Pickup", el: "Παραλαβή" },
      dt: { en: "21/02/2026 07:30", el: "21/02/2026 07:30" },
      carrier: "G. Pantazis",
      ci: "GP",
      rate: 540,
      ref: "EMET-104820",
      vehicle: { en: "Box truck", el: "Κλειστό φορτηγό" },
      weight: { en: "6,400 kg", el: "6.400 kg" },
      cargo: { en: "Juice cartons", el: "Κουτιά χυμού" },
      distance: "290 km",
      issue: null,
      notes: { en: "Delivery before 14:00", el: "Παράδοση πριν τις 14:00" },
      sortDate: 1771659000000
    },
    {
      sid: "SID-73020",
      from: "Ioannina",
      to: "Larissa",
      status: "upcoming",
      statusLabel: { en: "Upcoming", el: "Προσεχές" },
      statusClass: "sts-pending",
      ms: { en: "Pickup", el: "Παραλαβή" },
      dt: { en: "21/02/2026 08:00", el: "21/02/2026 08:00" },
      carrier: "M. Tsoukalas",
      ci: "MT",
      rate: 460,
      ref: "EMET-104821",
      vehicle: { en: "Tautliner", el: "Κουρτίνα" },
      weight: { en: "9,200 kg", el: "9.200 kg" },
      cargo: { en: "Beverages mix", el: "Μίγμα ποτών" },
      distance: "200 km",
      issue: null,
      notes: { en: "Multi-drop: Larissa + Volos", el: "Πολλαπλή παράδοση: Λάρισα + Βόλος" },
      sortDate: 1771660800000
    },
    {
      sid: "SID-73025",
      from: "Ioannina",
      to: "Kalamata",
      status: "upcoming",
      statusLabel: { en: "Upcoming", el: "Προσεχές" },
      statusClass: "sts-pending",
      ms: { en: "Pickup", el: "Παραλαβή" },
      dt: { en: "22/02/2026 06:00", el: "22/02/2026 06:00" },
      carrier: "KRP Transport",
      ci: "KR",
      rate: 780,
      ref: "11PAP-1031820",
      vehicle: { en: "Mega trailer", el: "Mega trailer" },
      weight: { en: "17,400 kg", el: "17.400 kg" },
      cargo: { en: "Water pallets", el: "Παλέτες νερού" },
      distance: "410 km",
      issue: null,
      notes: { en: "Long haul — driver rest required", el: "Μεγάλο δρομολόγιο — απαιτείται ανάπαυση οδηγού" },
      sortDate: 1771740000000
    },
    {
      sid: "SID-73026",
      from: "Ioannina",
      to: "Heraklion",
      status: "upcoming",
      statusLabel: { en: "Upcoming", el: "Προσεχές" },
      statusClass: "sts-pending",
      ms: { en: "Pickup", el: "Παραλαβή" },
      dt: { en: "22/02/2026 07:00", el: "22/02/2026 07:00" },
      carrier: "D. Ntinos",
      ci: "DN",
      rate: 1240,
      ref: "EMET-104830",
      vehicle: { en: "Refrigerated", el: "Ψυγείο" },
      weight: { en: "8,600 kg", el: "8.600 kg" },
      cargo: { en: "Dairy products", el: "Γαλακτοκομικά προϊόντα" },
      distance: "620 km",
      issue: null,
      notes: { en: "Ferry from Patras — Mon/Wed/Fri", el: "Ferry από Πάτρα — Δευτ/Τετ/Παρ" },
      sortDate: 1771743600000
    },
    {
      sid: "SID-73030",
      from: "Ioannina",
      to: "Corinth",
      status: "upcoming",
      statusLabel: { en: "Upcoming", el: "Προσεχές" },
      statusClass: "sts-pending",
      ms: { en: "Pickup", el: "Παραλαβή" },
      dt: { en: "23/02/2026 08:30", el: "23/02/2026 08:30" },
      carrier: "Gianneas N.",
      ci: "GN",
      rate: 520,
      ref: "EMET-104835",
      vehicle: { en: "Box truck", el: "Κλειστό φορτηγό" },
      weight: { en: "5,800 kg", el: "5.800 kg" },
      cargo: { en: "Beverages", el: "Ποτά" },
      distance: "260 km",
      issue: null,
      notes: { en: "New customer — first delivery", el: "Νέος πελάτης — πρώτη παράδοση" },
      sortDate: 1771835400000
    }
  ],

  // Tab 2: In Transit
  2: [
    {
      sid: "SID-90969",
      from: "Ioannina",
      to: "Livadeia",
      status: "transit",
      statusLabel: { en: "In Transit", el: "Σε μεταφορά" },
      statusClass: "sts-transit",
      ms: { en: "Delivery", el: "Παράδοση" },
      dt: { en: "21/02/2026 14:00", el: "21/02/2026 14:00" },
      carrier: "KRP Transport",
      ci: "KR",
      rate: 920,
      ref: "11PAP-1031772",
      vehicle: { en: "Tautliner 13.6m", el: "Κουρτίνα 13.6μ" },
      weight: { en: "14,200 kg", el: "14.200 kg" },
      cargo: { en: "Water bottles mixed", el: "Μπουκάλια νερού ανάμικτα" },
      distance: "285 km",
      issue: null,
      notes: { en: "ETA on track — last GPS 10:02", el: "ETA εντός χρόνου — τελευταίο GPS 10:02" },
      sortDate: 1771682400000
    },
    {
      sid: "SID-77478",
      from: "Ioannina",
      to: "Keratea",
      status: "transit",
      statusLabel: { en: "In Transit", el: "Σε μεταφορά" },
      statusClass: "sts-transit",
      ms: { en: "Delivery", el: "Παράδοση" },
      dt: { en: "21/02/2026 14:00", el: "21/02/2026 14:00" },
      carrier: "D. Ntinos",
      ci: "DN",
      rate: 600,
      ref: "11PAP-1031753",
      vehicle: { en: "Box truck 7.5T", el: "Κλειστό φορτηγό 7.5Τ" },
      weight: { en: "4,800 kg", el: "4.800 kg" },
      cargo: { en: "Juice bottles", el: "Μπουκάλια χυμού" },
      distance: "340 km",
      issue: null,
      notes: { en: "POLYZOS warehouse — gate code 4488", el: "Αποθήκη ΠΟΛΥΖΟΣ — κωδικός πύλης 4488" },
      sortDate: 1771682400001
    },
    {
      sid: "SID-13997",
      from: "Ioannina",
      to: "Trikala",
      status: "delayed",
      statusLabel: { en: "Delayed 45 min", el: "Καθυστέρηση 45 λεπτά" },
      statusClass: "sts-risk",
      ms: { en: "Delivery", el: "Παράδοση" },
      dt: { en: "21/02/2026 16:45", el: "21/02/2026 16:45" },
      carrier: "KRP Transport",
      ci: "KR",
      rate: 320,
      ref: "—",
      vehicle: { en: "Van", el: "Βαν" },
      weight: { en: "1,800 kg", el: "1.800 kg" },
      cargo: { en: "Sample cases", el: "Κιβώτια δειγμάτων" },
      distance: "95 km",
      issue: { en: "Traffic delay on Egnatia near Metsovo", el: "Καθυστέρηση λόγω κίνησης στην Εγνατία κοντά στο Μέτσοβο" },
      notes: { en: "Customer notified of delay", el: "Ο πελάτης ειδοποιήθηκε για την καθυστέρηση" },
      sortDate: 1771692300000
    }
  ],

  // Tab 3: Delivered
  3: [
    {
      sid: "SID-77301",
      from: "Ioannina",
      to: "Athens",
      status: "delivered",
      statusLabel: { en: "Delivered", el: "Παραδόθηκε" },
      statusClass: "sts-ok",
      ms: { en: "Completed", el: "Ολοκληρώθηκε" },
      dt: { en: "20/02/2026 15:30", el: "20/02/2026 15:30" },
      carrier: "KRP Transport",
      ci: "KR",
      rate: 840,
      ref: "11PAP-1031741",
      vehicle: { en: "Mega trailer", el: "Mega trailer" },
      weight: { en: "16,000 kg", el: "16.000 kg" },
      cargo: { en: "Water pallets", el: "Παλέτες νερού" },
      distance: "390 km",
      issue: null,
      notes: { en: "POD uploaded ✓ — Invoice pending", el: "Το POD ανέβηκε ✓ — Εκκρεμεί τιμολόγηση" },
      sortDate: 1771601400000
    },
    {
      sid: "SID-76998",
      from: "Ioannina",
      to: "Patras",
      status: "delivered",
      statusLabel: { en: "Delivered", el: "Παραδόθηκε" },
      statusClass: "sts-ok",
      ms: { en: "Completed", el: "Ολοκληρώθηκε" },
      dt: { en: "20/02/2026 12:15", el: "20/02/2026 12:15" },
      carrier: "G. Pantazis",
      ci: "GP",
      rate: 520,
      ref: "EMET-104760",
      vehicle: { en: "Tautliner", el: "Κουρτίνα" },
      weight: { en: "10,400 kg", el: "10.400 kg" },
      cargo: { en: "Beverages", el: "Ποτά" },
      distance: "220 km",
      issue: null,
      notes: { en: "On time ✓ — Rated 5/5", el: "Στην ώρα του ✓ — Βαθμολογία 5/5" },
      sortDate: 1771589700000
    },
    {
      sid: "SID-75412",
      from: "Ioannina",
      to: "Lamia",
      status: "delivered",
      statusLabel: { en: "Delivered", el: "Παραδόθηκε" },
      statusClass: "sts-ok",
      ms: { en: "Completed", el: "Ολοκληρώθηκε" },
      dt: { en: "19/02/2026 16:45", el: "19/02/2026 16:45" },
      carrier: "M. Tsoukalas",
      ci: "MT",
      rate: 440,
      ref: "EMET-104745",
      vehicle: { en: "Box truck", el: "Κλειστό φορτηγό" },
      weight: { en: "6,200 kg", el: "6.200 kg" },
      cargo: { en: "PET preforms", el: "Προπλάσματα PET" },
      distance: "190 km",
      issue: null,
      notes: { en: "Invoice #INV-4421 — Paid ✓", el: "Τιμολόγιο #INV-4421 — Πληρώθηκε ✓" },
      sortDate: 1771519500000
    },
    {
      sid: "SID-74890",
      from: "Ioannina",
      to: "Thessaloniki",
      status: "delivered",
      statusLabel: { en: "Delivered", el: "Παραδόθηκε" },
      statusClass: "sts-ok",
      ms: { en: "Completed", el: "Ολοκληρώθηκε" },
      dt: { en: "19/02/2026 11:00", el: "19/02/2026 11:00" },
      carrier: "KRP Transport",
      ci: "KR",
      rate: 780,
      ref: "11PAP-1031720",
      vehicle: { en: "Mega trailer", el: "Mega trailer" },
      weight: { en: "17,200 kg", el: "17.200 kg" },
      cargo: { en: "Mixed beverages", el: "Ανάμικτα ποτά" },
      distance: "280 km",
      issue: null,
      notes: { en: "15 min late — within tolerance", el: "15 λεπτά καθυστέρηση — εντός ορίων" },
      sortDate: 1771498800000
    },
    {
      sid: "SID-74201",
      from: "Ioannina",
      to: "Chalkida",
      status: "delivered",
      statusLabel: { en: "Delivered", el: "Παραδόθηκε" },
      statusClass: "sts-ok",
      ms: { en: "Completed", el: "Ολοκληρώθηκε" },
      dt: { en: "18/02/2026 14:20", el: "18/02/2026 14:20" },
      carrier: "Gianneas N.",
      ci: "GN",
      rate: 540,
      ref: "EMET-104730",
      vehicle: { en: "Box truck", el: "Κλειστό φορτηγό" },
      weight: { en: "5,800 kg", el: "5.800 kg" },
      cargo: { en: "Juice cartons", el: "Κουτιά χυμού" },
      distance: "290 km",
      issue: null,
      notes: { en: "New route — 30 min faster than estimate", el: "Νέα διαδρομή — 30 λεπτά ταχύτερη από την εκτίμηση" },
      sortDate: 1771424400000
    },
    {
      sid: "SID-73988",
      from: "Ioannina",
      to: "Corfu",
      status: "delivered",
      statusLabel: { en: "Delivered", el: "Παραδόθηκε" },
      statusClass: "sts-ok",
      ms: { en: "Completed", el: "Ολοκληρώθηκε" },
      dt: { en: "18/02/2026 09:00", el: "18/02/2026 09:00" },
      carrier: "D. Ntinos",
      ci: "DN",
      rate: 380,
      ref: "EMET-104715",
      vehicle: { en: "Van", el: "Βαν" },
      weight: { en: "2,200 kg", el: "2.200 kg" },
      cargo: { en: "Samples", el: "Δείγματα" },
      distance: "210 km",
      issue: null,
      notes: { en: "Ferry + delivery — complex route ✓", el: "Ferry + παράδοση — σύνθετη διαδρομή ✓" },
      sortDate: 1771405200000
    },
    {
      sid: "SID-73501",
      from: "Ioannina",
      to: "Volos",
      status: "delivered",
      statusLabel: { en: "Delivered", el: "Παραδόθηκε" },
      statusClass: "sts-ok",
      ms: { en: "Completed", el: "Ολοκληρώθηκε" },
      dt: { en: "17/02/2026 16:00", el: "17/02/2026 16:00" },
      carrier: "KRP Transport",
      ci: "KR",
      rate: 460,
      ref: "11PAP-1031700",
      vehicle: { en: "Tautliner", el: "Κουρτίνα" },
      weight: { en: "12,000 kg", el: "12.000 kg" },
      cargo: { en: "Water 1.5L", el: "Νερό 1.5L" },
      distance: "200 km",
      issue: null,
      notes: { en: "Routine delivery", el: "Καθημερινή παράδοση" },
      sortDate: 1771344000000
    },
    {
      sid: "SID-73220",
      from: "Ioannina",
      to: "Agrinio",
      status: "delivered",
      statusLabel: { en: "Delivered", el: "Παραδόθηκε" },
      statusClass: "sts-ok",
      ms: { en: "Completed", el: "Ολοκληρώθηκε" },
      dt: { en: "17/02/2026 11:30", el: "17/02/2026 11:30" },
      carrier: "G. Pantazis",
      ci: "GP",
      rate: 340,
      ref: "EMET-104698",
      vehicle: { en: "Box truck", el: "Κλειστό φορτηγό" },
      weight: { en: "4,600 kg", el: "4.600 kg" },
      cargo: { en: "Olive oil", el: "Ελαιόλαδο" },
      distance: "130 km",
      issue: null,
      notes: { en: "Short haul — same-day delivery", el: "Σύντομο δρομολόγιο — παράδοση αυθημερόν" },
      sortDate: 1771327800000
    },
    {
      sid: "SID-72888",
      from: "Ioannina",
      to: "Preveza",
      status: "delivered",
      statusLabel: { en: "Delivered", el: "Παραδόθηκε" },
      statusClass: "sts-ok",
      ms: { en: "Completed", el: "Ολοκληρώθηκε" },
      dt: { en: "16/02/2026 14:00", el: "16/02/2026 14:00" },
      carrier: "M. Tsoukalas",
      ci: "MT",
      rate: 280,
      ref: "EMET-104680",
      vehicle: { en: "Van", el: "Βαν" },
      weight: { en: "1,600 kg", el: "1.600 kg" },
      cargo: { en: "Sample packs", el: "Πακέτα δειγμάτων" },
      distance: "95 km",
      issue: null,
      notes: { en: "Local delivery", el: "Τοπική παράδοση" },
      sortDate: 1771250400000
    }
  ],

  // Tab 4: Billing
  4: [
    {
      sid: "SID-71004",
      from: "Ioannina",
      to: "Kalamata",
      status: "billing",
      statusLabel: { en: "Invoice Dispute", el: "Διαφωνία Τιμολογίου" },
      statusClass: "sts-warn",
      ms: { en: "Resolve by", el: "Επίλυση έως" },
      dt: { en: "25/02", el: "25/02" },
      carrier: "KRP Transport",
      ci: "KR",
      rate: 780,
      ref: "INV-4398",
      vehicle: { en: "Mega trailer", el: "Mega trailer" },
      weight: { en: "16,800 kg", el: "16.800 kg" },
      cargo: { en: "Water pallets", el: "Παλέτες νερού" },
      distance: "410 km",
      issue: { en: "Carrier invoiced €820 — agreed rate was €780", el: "Ο μεταφορέας τιμολόγησε €820 — η συμφωνημένη τιμή ήταν €780" },
      notes: { en: "Dispute open since 15/02", el: "Διαφωνία ανοιχτή από τις 15/02" },
      sortDate: 1772006400000
    },
    {
      sid: "SID-70501",
      from: "Ioannina",
      to: "Athens",
      status: "billing",
      statusLabel: { en: "Payment Due", el: "Ληξιπρόθεσμη Πληρωμή" },
      statusClass: "sts-warn",
      ms: { en: "Due", el: "Λήξη" },
      dt: { en: "28/02", el: "28/02" },
      carrier: "D. Ntinos",
      ci: "DN",
      rate: 600,
      ref: "INV-4385",
      vehicle: { en: "Box truck", el: "Κλειστό φορτηγό" },
      weight: { en: "4,200 kg", el: "4.200 kg" },
      cargo: { en: "Juice bottles", el: "Μπουκάλια χυμού" },
      distance: "390 km",
      issue: { en: "Invoice approved — awaiting payment transfer", el: "Το τιμολόγιο εγκρίθηκε — αναμένεται μεταφορά πληρωμής" },
      notes: { en: "Net 30 terms", el: "Όροι Net 30" },
      sortDate: 1772265600000
    }
  ]
};

export const TAB_COUNTS = [5, 9, 3, 556, 2];
